apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  ports:
    - port: 3000
      name: main
      protocol: TCP
      targetPort: 3000
  selector:
    run: webapp
  type: LoadBalancer
